import type { Metadata } from "next";
import { Inter } from "next/font/google";
import classNames from "classnames";
import {} from "next/navigation";
import "bootstrap/dist/css/bootstrap.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Demo App",
  description: "Generated by next",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={classNames(inter.className)}>
        <nav className="navbar navbar-expand-lg navbar-dark bg-success p-2">
          <a className="navbar-brand" href="#">
            JPWP
          </a>
        </nav>
        <div className="container-fluid py-2">{children}</div>
      </body>
    </html>
  );
}
